# Generated by Django 3.1.5 on 2021-04-06 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='DDC',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.CreateModel(
            name='BookClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('DDC', models.DecimalField(decimal_places=4, max_digits=8)),
                ('OWI', models.CharField(max_length=20)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
