# Generated by Django 3.1.5 on 2021-06-08 19:07

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommend', '0002_auto_20210406_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodReadsImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BooksDisplayed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author_first', models.CharField(max_length=100)),
                ('author_last', models.CharField(max_length=100)),
                ('classify_ISBN', models.CharField(max_length=13)),
                ('classify_DDC', models.DecimalField(decimal_places=3, max_digits=8)),
                ('pages', models.IntegerField(max_length=9999)),
                ('publish_date', models.IntegerField(max_length=9999)),
                ('country', models.CharField(max_length=100)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=list, null=True, size=20)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
