"""empty message

Revision ID: 605ed4dd4197
Revises: 1d22cf30ffc7
Create Date: 2021-07-06 14:16:02.836884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605ed4dd4197'
down_revision = '1d22cf30ffc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'author_last')
    op.drop_column('books', 'author_first')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author_first', sa.VARCHAR(), nullable=True))
    op.add_column('books', sa.Column('author_last', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
