"""empty message

Revision ID: 8cbe23b4c39e
Revises: 
Create Date: 2021-08-03 17:23:14.291629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cbe23b4c39e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hundred_categories_DDC',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_number', sa.String(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thousand_categories_DDC',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_number', sa.String(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thousand_categories_DDC')
    op.drop_table('hundred_categories_DDC')
    # ### end Alembic commands ###
