"""empty message

Revision ID: 979e8fca5d8d
Revises: 09cfc03b9027
Create Date: 2021-07-05 16:27:41.379035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979e8fca5d8d'
down_revision = '09cfc03b9027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('book_id', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('author', sa.String(), nullable=True))
    op.add_column('books', sa.Column('additional_authors', sa.String(), nullable=True))
    op.add_column('books', sa.Column('isbn', sa.String(), nullable=True))
    op.add_column('books', sa.Column('isbn13', sa.String(), nullable=True))
    op.add_column('books', sa.Column('my_rating', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('avg_rating', sa.Float(), nullable=True))
    op.add_column('books', sa.Column('publisher', sa.String(), nullable=True))
    op.add_column('books', sa.Column('binding', sa.String(), nullable=True))
    op.add_column('books', sa.Column('pages', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('year_publish', sa.String(), nullable=True))
    op.add_column('books', sa.Column('year_publish_original', sa.String(), nullable=True))
    op.add_column('books', sa.Column('date_read', sa.String(), nullable=True))
    op.add_column('books', sa.Column('date_added', sa.String(), nullable=True))
    op.add_column('books', sa.Column('bookshelves', sa.String(), nullable=True))
    op.drop_column('books', 'author_last')
    op.drop_column('books', 'author_first')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author_first', sa.VARCHAR(), nullable=True))
    op.add_column('books', sa.Column('author_last', sa.VARCHAR(), nullable=True))
    op.drop_column('books', 'bookshelves')
    op.drop_column('books', 'date_added')
    op.drop_column('books', 'date_read')
    op.drop_column('books', 'year_publish_original')
    op.drop_column('books', 'year_publish')
    op.drop_column('books', 'pages')
    op.drop_column('books', 'binding')
    op.drop_column('books', 'publisher')
    op.drop_column('books', 'avg_rating')
    op.drop_column('books', 'my_rating')
    op.drop_column('books', 'isbn13')
    op.drop_column('books', 'isbn')
    op.drop_column('books', 'additional_authors')
    op.drop_column('books', 'author')
    op.drop_column('books', 'book_id')
    # ### end Alembic commands ###
