"""empty message

Revision ID: c99b0d3b05f2
Revises: 8cbe23b4c39e
Create Date: 2021-08-03 17:48:48.887823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99b0d3b05f2'
down_revision = '8cbe23b4c39e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('classify_hundred_id', sa.String(), nullable=True))
    op.add_column('books', sa.Column('classify_thousand_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'books', 'thousand_categories_DDC', ['classify_thousand_id'], ['id'])
    op.create_foreign_key(None, 'books', 'hundred_categories_DDC', ['classify_hundred_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'classify_thousand_id')
    op.drop_column('books', 'classify_hundred_id')
    # ### end Alembic commands ###
